# Group Data and Aggregating Variables Exercise

# Task 1 Importing Libraries and Dataframes

# Task 2 Find the mean for order id

# Task 3 How do the results for the entire dataframe differ from those of the subset?

# Task 4 Creating a loyalty flag for existing customers

# Task 5 Check the basic statistics of the product prices for each loyalty category

# Task 6 Create a spending flag

# Task 7 Creating order freq. flag

# Export Dataset

---------

# Task 1 Importing Libraries and Dataframes

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
#pathway to datasets
path =(r'C:\Users\colmu\Desktop\Career Foundry\Achievement 4\Instacart Basket Analysis\Data')

In [6]:
#Importing dataset
ords_prods_merge=pd.read_pickle(os.path.join(path,'Prepared Data','orders_products_merged.pkl'))

In [5]:
18663868+7790795+5950196

32404859

In [4]:
ords_prods_merge.count()

order_id                  32404859
user_id                   32404859
clients_order_number      32404859
orders_day_of_week        32404859
order_hour_of_day         32404859
days_since_prior_order    30328763
product_id                32404859
add_to_cart_order         32404859
reordered                 32404859
product_name              32404859
aisle_id                  32404859
department_id             32404859
prices                    32404859
price_range_loc           32404859
busiest_period_of_day     32404859
busiest_days              32404859
loyalty_flag              32404859
spending_flag             32404859
FRQ_prior_order_flag      32404854
dtype: int64

In [26]:
#checking outliers
df_high= ords_prods_merge.loc[ords_prods_merge['prices'] >= 100]

In [34]:
df_high = df_high[['order_id','prices']]

In [35]:
df_high

          order_id   prices
10030345    912404  14900.0
10030346    603376  14900.0
10030347   3264360  14900.0
10030348    892534  14900.0
10030349    229704  14900.0
...            ...      ...
29166209   2249946  99999.0
29166210   2363282  99999.0
29166211   3181945  99999.0
29166212   2486215  99999.0
29166213   2232716  99999.0

[5127 rows x 2 columns]

# Task 2 Find the mean for order id

In [31]:
#agg mean of order_number
ords_prods_merge.groupby('user_id').agg({'clients_order_number': ['mean']})

        clients_order_number
                        mean
user_id
1                   5.813559
2                   8.035897
3                   6.000000
4                   2.888889
5                   2.486486
...                      ...
206205              1.687500
206206             38.007018
206207              8.116592
206208             25.505170
206209              6.937984

[206209 rows x 1 columns]

# Task 3 How do the results for the entire dataframe differ from those of the subset?

In [6]:
# Comparatively to the subset, the above data output is more complex and has more variables present it could pull from. The values for the mean are also different since it is pullng from more data (E.g. 4 was previously 18.8 and is now 17.8)

# Task 4 Creating a loyalty flag for existing customers

### Creating max_order column

In [32]:
#creating max order column
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['clients_order_number'].transform(np.max)

C:\Users\colmu\AppData\Local\Temp\ipykernel_4388\2515391940.py:2: FutureWarning: The provided callable <function amax at 0x000001D953AF1BC0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['clients_order_number'].transform(np.max)

In [33]:
#check max_order clmn
ords_prods_merge.head(100)

,order_id,user_id,clients_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_period_of_day,busiest_days,max_order,loyalty_flag,spending_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,10,New customer,High spender
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,10,New customer,High spender
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,10,New customer,High spender
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,10,New customer,High spender
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,10,New customer,High spender
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,10,New customer,High spender
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,10,New customer,High spender
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender
10,2968173,15,15,1,9,7.0,196,2,0,Soda,77,7,9.0,Mid-range product,least orders,busiests days,22,Regular customer,Low spender
11,1870022,15,17,2,16,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,22,Regular customer,Low spender
12,1911383,15,18,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,22,Regular customer,Low spender
13,2715276,15,21,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,22,Regular customer,Low spender
14,487368,15,22,1,10,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,22,Regular customer,Low spender
15,2293453,19,2,5,14,6.0,196,3,0,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,9,New customer,High spender
16,1973799,19,5,6,12,8.0,196,15,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,9,New customer,High spender
17,532817,19,7,4,17,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,average orders,least busy days,9,New customer,High spender
18,1573906,21,10,3,10,6.0,196,2,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,33,Regular customer,High spender
19,1593000,31,10,3,8,7.0,196,17,0,Soda,77,7,9.0,Mid-range product,least orders,least busy days,20,Regular customer,High spender
20,2231262,31,17,3,11,8.0,196,14,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,20,Regular customer,High spender
21,2580647,43,6,4,16,4.0,196,9,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,11,Regular customer,High spender
22,2187180,43,9,4,12,3.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,11,Regular customer,High spender
23,2497897,52,1,1,9,NaN,196,4,0,Soda,77,7,9.0,Mid-range product,least orders,busiests days,27,Regular customer,High spender
24,1318871,52,2,1,10,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,27,Regular customer,High spender
25,1261384,52,3,1,10,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,27,Regular customer,High spender
26,580568,52,5,2,10,8.0,196,6,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
27,2428073,52,7,2,7,8.0,196,5,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,27,Regular customer,High spender
28,342306,52,9,1,11,7.0,196,5,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,27,Regular customer,High spender
29,1520353,52,10,2,10,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
30,2542086,52,11,2,9,7.0,196,3,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,27,Regular customer,High spender
31,944694,52,12,1,16,6.0,196,7,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,27,Regular customer,High spender
32,1268191,52,15,2,11,8.0,196,3,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
33,1122089,52,17,2,10,6.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
34,1498922,52,18,2,10,14.0,196,6,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
35,180919,52,19,3,8,8.0,196,4,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,27,Regular customer,High spender
36,2695875,52,21,5,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,27,Regular customer,High spender
37,3205960,67,1,3,11,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,24,Regular customer,High spender
38,970922,67,2,1,15,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
39,596585,67,3,1,13,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
40,2037087,67,4,2,9,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,24,Regular customer,High spender
41,2474111,67,5,3,14,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,24,Regular customer,High spender
42,1568481,67,6,3,12,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,24,Regular customer,High spender
43,2048527,67,8,2,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,24,Regular customer,High spender
44,2389031,67,9,2,14,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,24,Regular customer,High spender
45,2378562,67,10,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
46,1515698,67,11,1,11,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
47,1928050,67,12,2,12,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,24,Regular customer,High spender
48,1949274,67,13,1,10,6.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
49,551869,67,14,1,9,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,24,Regular customer,High spender
50,768572,67,16,4,10,9.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,24,Regular customer,High spender
51,150528,67,18,5,16,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,24,Regular customer,High spender
52,29758,67,19,0,14,9.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
53,1558976,67,21,1,9,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,24,Regular customer,High spender
54,863974,67,22,1,11,14.0,196,3,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
55,2308399,67,23,1,14,14.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,24,Regular customer,High spender
56,2759128,81,3,1,9,14.0,196,2,0,Soda,77,7,9.0,Mid-range product,least orders,busiests days,7,New customer,High spender
57,1812985,81,5,2,20,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,average orders,regularly busy days,7,New customer,High spender
58,1889835,82,1,3,15,NaN,196,6,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,19,Regular customer,High spender
59,499460,82,3,5,10,5.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,19,Regular customer,High spender
60,2728456,82,4,0,11,16.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,19,Regular customer,High spender
61,2653743,82,6,4,9,13.0,196,5,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,19,Regular customer,High spender
62,1358880,82,9,1,10,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,19,Regular customer,High spender
63,343588,82,10,2,11,1.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,19,Regular customer,High spender
64,3034663,82,15,2,11,12.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,19,Regular customer,High spender
65,147262,82,18,1,13,7.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,19,Regular customer,High spender
66,3144004,82,19,2,15,8.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,19,Regular customer,High spender
67,2126069,98,3,0,9,25.0,196,7,0,Soda,77,7,9.0,Mid-range product,least orders,busiests days,14,Regular customer,High spender
68,2210120,98,7,5,14,5.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,14,Regular customer,High spender
69,681011,98,9,3,9,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,14,Regular customer,High spender
70,2846344,98,11,4,13,15.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,14,Regular customer,High spender
71,747431,98,12,6,13,30.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,14,Regular customer,High spender
72,2383054,98,13,4,11,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,14,Regular customer,High spender
73,1993729,98,14,5,8,8.0,196,2,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,14,Regular customer,High spender
74,1403849,109,3,3,17,9.0,196,5,0,Soda,77,7,9.0,Mid-range product,average orders,least busy days,6,New customer,High spender
75,520620,120,1,3,11,NaN,196,2,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,3,New customer,High spender
76,3273029,120,3,2,8,19.0,196,2,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,3,New customer,High spender
77,1861943,185,2,1,12,25.0,196,10,0,Soda,77,7,9.0,Mid-range product,most orders,busiests days,6,New customer,High spender
78,2040988,195,1,1,14,NaN,196,2,0,Soda,77,7,9.0,Mid-range product,most orders,busiests days,58,Loyal customer,High spender
79,1680569,195,8,1,9,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,58,Loyal customer,High spender
80,276171,195,19,5,11,3.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,58,Loyal customer,High spender
81,2744976,195,22,5,10,7.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,58,Loyal customer,High spender
82,2781919,195,25,1,14,4.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,58,Loyal customer,High spender
83,1738718,195,31,2,8,4.0,196,2,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,58,Loyal customer,High spender
84,3058369,195,34,3,10,6.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,58,Loyal customer,High spender
85,1485596,195,37,2,15,0.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,58,Loyal customer,High spender
86,417035,195,40,3,16,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,58,Loyal customer,High spender
87,1615297,195,47,5,10,2.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,58,Loyal customer,High spender
88,1765587,195,52,3,12,2.0,196,3,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,58,Loyal customer,High spender
89,745908,195,57,4,11,3.0,196,3,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,58,Loyal customer,High spender
90,2505656,222,17,2,12,1.0,196,2,0,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,70,Loyal customer,High spender
91,3268370,222,38,5,15,1.0,196,6,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,70,Loyal customer,High spender
92,2016711,290,9,5,19,6.0,196,8,0,Soda,77,7,9.0,Mid-range product,average orders,regularly busy days,51,Loyal customer,High spender
93,2706088,290,28,6,10,7.0,196,16,1,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,51,Loyal customer,High spender
94,1952286,331,6,5,16,30.0,196,8,0,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,8,New customer,High spender
95,3226575,360,1,5,12,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,most orders,regularly busy days,3,New customer,High spender
96,1469869,377,3,5,17,3.0,196,9,0,Soda,77,7,9.0,Mid-range product,average orders,regularly busy days,3,New customer,High spender
97,1927023,387,2,4,10,22.0,196,3,0,Soda,77,7,9.0,Mid-range product,most orders,least busy days,8,New customer,High spender
98,858092,420,4,1,19,30.0,196,2,0,Soda,77,7,9.0,Mid-range product,average orders,busiests days,22,Regular customer,High spender
99,119314,420,5,3,19,16.0,196,2,1,Soda,77,7,9.0,Mid-range product,average orders,least busy days,22,Regular customer,High spender

### creating a loyalty flag column

In [34]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [35]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [36]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [37]:
#value count loyalty customer
ords_prods_merge['loyalty_flag'].value_counts(dropna=False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [38]:
ords_prods_merge.head(10)

,order_id,user_id,clients_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_period_of_day,busiest_days,max_order,loyalty_flag,spending_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,10,New customer,High spender
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,10,New customer,High spender
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,10,New customer,High spender
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,10,New customer,High spender
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,10,New customer,High spender
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,10,New customer,High spender
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,10,New customer,High spender
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,10,New customer,High spender

# Task 5 Check the basic statistics of the product prices for each loyalty category

In [39]:
#calculating product prices for loyal customers
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'median', 'min', 'max']})

                     prices
                       mean median  min      max
loyalty_flag
Loyal customer    10.386336    7.4  1.0  99999.0
New customer      13.294670    7.4  1.0  99999.0
Regular customer  12.495717    7.4  1.0  99999.0

# Task 6 Create a spending flag

### Creating Mean column

In [42]:
### creating max order clm for prices
ords_prods_merge['mean_order'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

C:\Users\colmu\AppData\Local\Temp\ipykernel_4388\1655477330.py:2: FutureWarning: The provided callable <function mean at 0x000001D953AF28E0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  ords_prods_merge['mean_order'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [43]:
#check mean_order clmn
ords_prods_merge.head(10)

,order_id,user_id,clients_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_period_of_day,busiest_days,max_order,loyalty_flag,spending_flag,mean_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,6.367797,New customer,High spender,6.367797
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,High spender,6.367797
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,6.367797,New customer,High spender,6.367797
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,High spender,6.367797
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,most orders,least busy days,6.367797,New customer,High spender,6.367797
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,regularly busy days,6.367797,New customer,High spender,6.367797
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,busiests days,6.367797,New customer,High spender,6.367797
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,6.367797,New customer,High spender,6.367797
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,most orders,busiests days,6.367797,New customer,High spender,6.367797
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,High spender,6.367797

### Creating Spending flag clmn

In [44]:
ords_prods_merge.loc[ords_prods_merge['mean_order'] >= 10, 'spending_flag'] = 'High spender'

In [45]:
ords_prods_merge.loc[ords_prods_merge['mean_order'] < 10, 'spending_flag'] = 'Low spender'

In [46]:
#value count Spending flag
ords_prods_merge['spending_flag'].value_counts(dropna=False)

spending_flag
Low spender     31770614
High spender      634245
Name: count, dtype: int64

# Task 7 Creating order freq. flag

### Creating Freq column for days since prior order

In [95]:
# creating max order clm for prices
ords_prods_merge['frq_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

C:\Users\colmu\AppData\Local\Temp\ipykernel_4388\215396961.py:2: FutureWarning: The provided callable <function median at 0x000001D953C33880> is currently using SeriesGroupBy.median. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "median" instead.
  ords_prods_merge['frq_days_since_prior_order'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [50]:
#check frq_order clmn
ords_prods_merge.head(30)

,order_id,user_id,clients_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,department_id,prices,price_range_loc,busiest_period_of_day,busiest_days,max_order,loyalty_flag,spending_flag,mean_order,frq_order
0,2539329,1,1,2,8,NaN,196,1,0,Soda,...,7,9.0,Mid-range product,least orders,regularly busy days,6.367797,New customer,Low spender,6.367797,20.5
1,2398795,1,2,3,7,15.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,Low spender,6.367797,20.5
2,473747,1,3,3,12,21.0,196,1,1,Soda,...,7,9.0,Mid-range product,most orders,least busy days,6.367797,New customer,Low spender,6.367797,20.5
3,2254736,1,4,4,7,29.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,Low spender,6.367797,20.5
4,431534,1,5,4,15,28.0,196,1,1,Soda,...,7,9.0,Mid-range product,most orders,least busy days,6.367797,New customer,Low spender,6.367797,20.5
5,3367565,1,6,2,7,19.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,regularly busy days,6.367797,New customer,Low spender,6.367797,20.5
6,550135,1,7,1,9,20.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,busiests days,6.367797,New customer,Low spender,6.367797,20.5
7,3108588,1,8,1,14,14.0,196,2,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,6.367797,New customer,Low spender,6.367797,20.5
8,2295261,1,9,1,16,0.0,196,4,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,6.367797,New customer,Low spender,6.367797,20.5
9,2550362,1,10,4,8,30.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,least busy days,6.367797,New customer,Low spender,6.367797,20.5
10,2968173,15,15,1,9,7.0,196,2,0,Soda,...,7,9.0,Mid-range product,least orders,busiests days,3.980556,Regular customer,Low spender,3.980556,10.0
11,1870022,15,17,2,16,8.0,196,6,1,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,3.980556,Regular customer,Low spender,3.980556,10.0
12,1911383,15,18,2,11,7.0,196,1,1,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,3.980556,Regular customer,Low spender,3.980556,10.0
13,2715276,15,21,1,9,7.0,196,1,1,Soda,...,7,9.0,Mid-range product,least orders,busiests days,3.980556,Regular customer,Low spender,3.980556,10.0
14,487368,15,22,1,10,14.0,196,1,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,3.980556,Regular customer,Low spender,3.980556,10.0
15,2293453,19,2,5,14,6.0,196,3,0,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,8.372059,New customer,Low spender,8.372059,6.0
16,1973799,19,5,6,12,8.0,196,15,1,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,8.372059,New customer,Low spender,8.372059,6.0
17,532817,19,7,4,17,6.0,196,1,1,Soda,...,7,9.0,Mid-range product,average orders,least busy days,8.372059,New customer,Low spender,8.372059,6.0
18,1573906,21,10,3,10,6.0,196,2,0,Soda,...,7,9.0,Mid-range product,most orders,least busy days,7.012683,Regular customer,Low spender,7.012683,7.5
19,1593000,31,10,3,8,7.0,196,17,0,Soda,...,7,9.0,Mid-range product,least orders,least busy days,8.137793,Regular customer,Low spender,8.137793,6.0
20,2231262,31,17,3,11,8.0,196,14,1,Soda,...,7,9.0,Mid-range product,most orders,least busy days,8.137793,Regular customer,Low spender,8.137793,6.0
21,2580647,43,6,4,16,4.0,196,9,0,Soda,...,7,9.0,Mid-range product,most orders,least busy days,7.444898,Regular customer,Low spender,7.444898,10.0
22,2187180,43,9,4,12,3.0,196,1,1,Soda,...,7,9.0,Mid-range product,most orders,least busy days,7.444898,Regular customer,Low spender,7.444898,10.0
23,2497897,52,1,1,9,NaN,196,4,0,Soda,...,7,9.0,Mid-range product,least orders,busiests days,6.356287,Regular customer,Low spender,6.356287,8.0
24,1318871,52,2,1,10,7.0,196,5,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,6.356287,Regular customer,Low spender,6.356287,8.0
25,1261384,52,3,1,10,7.0,196,3,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,6.356287,Regular customer,Low spender,6.356287,8.0
26,580568,52,5,2,10,8.0,196,6,1,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,6.356287,Regular customer,Low spender,6.356287,8.0
27,2428073,52,7,2,7,8.0,196,5,1,Soda,...,7,9.0,Mid-range product,least orders,regularly busy days,6.356287,Regular customer,Low spender,6.356287,8.0
28,342306,52,9,1,11,7.0,196,5,1,Soda,...,7,9.0,Mid-range product,most orders,busiests days,6.356287,Regular customer,Low spender,6.356287,8.0
29,1520353,52,10,2,10,8.0,196,4,1,Soda,...,7,9.0,Mid-range product,most orders,regularly busy days,6.356287,Regular customer,Low spender,6.356287,8.0

### Creating Freq flag

In [103]:
ords_prods_merge.loc[ords_prods_merge['frq_days_since_prior_order'] <= 10, 'FRQ_prior_order_flag'] = 'Frequent customer'

In [102]:
ords_prods_merge.loc[(ords_prods_merge['frq_days_since_prior_order'] <= 20) & (ords_prods_merge['frq_days_since_prior_order'] > 10), 'FRQ_prior_order_flag'] = 'Regular customer'

In [104]:
ords_prods_merge.loc[ords_prods_merge['frq_days_since_prior_order'] > 20, 'FRQ_prior_order_flag'] = 'Non-frequent customer'

In [105]:
#value count Spending flag
ords_prods_merge['FRQ_prior_order_flag'].value_counts(dropna=False)

FRQ_prior_order_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
NaN                             5
Name: count, dtype: int64

In [106]:
#creating sub-set to evaluate nan values
df_prior_order_frq= ords_prods_merge[ords_prods_merge['FRQ_prior_order_flag'].isnull() == True]

In [107]:
# User 159838 will be left as days between orders are populating as NaN impacting frequency
df_prior_order_frq.head()

,order_id,user_id,clients_order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,busiest_days,max_order,loyalty_flag,spending_flag,mean_order,frq_order,frequency__flag,frequency_flag,frq_days_since_prior_order,FRQ_prior_order_flag
13645692,895835,159838,1,0,17,NaN,10749,3,0,Organic Red Bell Pepper,...,busiests days,7.42,New customer,Low spender,7.42,NaN,NaN,NaN,NaN,NaN
17251990,895835,159838,1,0,17,NaN,33401,6,0,Goat Cheese Crumbles,...,busiests days,7.42,New customer,Low spender,7.42,NaN,NaN,NaN,NaN,NaN
17622767,895835,159838,1,0,17,NaN,23695,2,0,California Veggie Burger,...,busiests days,7.42,New customer,Low spender,7.42,NaN,NaN,NaN,NaN,NaN
24138593,895835,159838,1,0,17,NaN,21334,5,0,Organic Peeled Garlic,...,busiests days,7.42,New customer,Low spender,7.42,NaN,NaN,NaN,NaN,NaN
25880002,895835,159838,1,0,17,NaN,22198,1,0,4X Ultra Concentrated Natural Laundry Detergen...,...,busiests days,7.42,New customer,Low spender,7.42,NaN,NaN,NaN,NaN,NaN

# Export Dataset

In [122]:
#Export df_ords_prods_merge into a pickle
ords_prods_merge.to_pickle(os.path.join(path,'Prepared Data', 'orders_products_merged.pkl'))